Adds Via feature to flask.Markup.escape
facebook/pyre-check pull request #442
Opened 2021-07-06 11:36 UTC by abishekvashok

Adds via escape_html feature to flask.Markup.escape

The other possible sink for flask.Markup was already implemented as both
flask and Jinja2 share the same library.

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>
Fixes: https://github.com/MLH-Fellowship/pyre-check/issues/15

Before the change: 
<img width="1440" alt="Screenshot 2021-07-06 at 4 34 18 PM" src="https://user-images.githubusercontent.com/8947010/124593528-606d0300-de7c-11eb-829b-a38c7cf7777f.png">

After the change:
<img width="1440" alt="Screenshot 2021-07-06 at 5 05 54 PM" src="https://user-images.githubusercontent.com/8947010/124593614-7aa6e100-de7c-11eb-802e-8de8c3b47897.png">

2021-07-06 19:58 UTC, gbleaney requested changes
Thanks for the PR! And I really appreciate that you included evidence of your testing :)

2021-07-06 19:58 UTC, gbleaney commented on stubs/third_party_taint/xss_sinks.pysa
> +def markupsafe.Markup.escape(s: TaintInTaintOut[Via[escape_html]]): ...
Two tweaks we should make here:
1) Adding `@SkipObscure`. This is something we just released, and is documented here: https://pyre-check.org/docs/pysa-advanced#obscure-models . We want `SkipObscure` as a temporary workaround for this issue that's preventing us from getting `always-via:escape_html` (you'll notice in your test we're only getting `via:escape_html`)
2) Adding `LocalReturn`. This is so we actually propagate taint from `s` to the return value, despite the `SkipObscure` we're adding. Documented here: https://pyre-check.org/docs/pysa-basics#taint-propagation

```suggestion
@SkipObscure
def markupsafe.Markup.escape(s: TaintInTaintOut[LocalReturn, Via[escape_html]]): ...
```

2021-07-07 04:41 UTC, abishekvashok commented
@gbleaney thanks for the suggestions, the changes have been made!

<img width="1440" alt="Screenshot 2021-07-07 at 10 09 22 AM" src="https://user-images.githubusercontent.com/8947010/124701087-90afb280-df0b-11eb-834a-c86e1d67042d.png">

2021-07-07 14:04 UTC, gbleaney commented
Thanks @abishekvashok! One final thing: can you update your test plan? I believe it should show an `always-via:escape_html` now, and I'd like to confirm that's the case

2021-07-07 14:13 UTC, abishekvashok commented
>  I believe it should show an always-via:escape_html now, and I'd like to confirm that's the case

@gbleaney Hmm, I am a bit clueless now. I believe I got it in the screenshot posted above. I'll repost again,

![](https://user-images.githubusercontent.com/8947010/124701087-90afb280-df0b-11eb-834a-c86e1d67042d.png)

But I don't know -- sorry -- were you suggesting I run a specific test or something?

2021-07-07 14:25 UTC, abishekvashok commented
Upss sorry @gbleaney, I should have used the same test plan! Here's the output anyway, I hope this is what you seek :)
<img width="1440" alt="Screenshot 2021-07-07 at 7 53 35 PM" src="https://user-images.githubusercontent.com/8947010/124776557-2aec1680-df5d-11eb-9656-8bc89dbfb815.png">

2021-07-07 14:36 UTC, gbleaney commented
Yup, looks perfect now :)

2021-07-07 15:02 UTC, closed without merging