Adds missing models and stubs for lxml
facebook/pyre-check pull request #450
Opened 2021-07-12 09:42 UTC by abishekvashok

Adds missing models and stubs for lxml.

Modifies existing stubs of lxml function `lxml.etree.fromstring` to
include the optional arguments `parser` and `base_url`.

Adds stubs for the function `lxml.etree.fromstringlist`

Adds Pysa models for the function `lxml.etree.fromstringlist` and
declare its input string list argument as an `XMLParser` sink.

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>
Fixes: https://github.com/MLH-Fellowship/pyre-check/issues/23

2021-07-12 09:48 UTC, abishekvashok commented
lxml stubs have been modified to further reflect the stubs they maintain: https://github.com/lxml/lxml-stubs/blob/master/lxml-stubs/etree.pyi. Those stubs are not available in typeshed due to some issues. However, the current stubs can be removed when they get integrated into typeshed so we won't have duplicates. For now, I added additional definitions Pysa. This helps us catch issues when we specify the optional parser parameter which otherwise Pysa won't catch.

Before the changes:
<img width="1155" alt="lxml-b-1" src="https://user-images.githubusercontent.com/8947010/125267057-11afe500-e324-11eb-930a-23ef59c33d61.png">
<img width="1162" alt="lxml-b-2" src="https://user-images.githubusercontent.com/8947010/125267079-17a5c600-e324-11eb-85ed-ab03ced05d1a.png">
<img width="1161" alt="lxml-b3" src="https://user-images.githubusercontent.com/8947010/125267083-18d6f300-e324-11eb-83de-206e2d42e697.png">

After the changes:
<img width="1163" alt="lxml-a-1" src="https://user-images.githubusercontent.com/8947010/125267181-2f7d4a00-e324-11eb-958c-e697e81b5245.png">
<img width="1165" alt="lxml-a-2" src="https://user-images.githubusercontent.com/8947010/125267201-34da9480-e324-11eb-93e3-06ea4beb12bc.png">
<img width="1440" alt="lxml-a-3" src="https://user-images.githubusercontent.com/8947010/125267214-37d58500-e324-11eb-9b19-ea794697724e.png">

2021-07-13 17:17 UTC, gbleaney requested changes

2021-07-13 17:17 UTC, gbleaney commented on stubs/third_party_taint/lxml_sinks.pysa
> +def lxml.etree.fromstring(input: TaintSink[XMLParser], parser, *, base_url): ...
These extra parameters are actually not required by Pysa, and they make the model harder to maintain (more things to keep in sync with the stub), so we prefer to not include them.

(Apply throughout the diff)

```suggestion
def lxml.etree.fromstring(input: TaintSink[XMLParser]): ...
```

2021-07-13 17:42 UTC, abishekvashok commented
@gbleaney Done :D

2021-07-14 09:24 UTC, closed without merging