Clean up unclassified errors in the model parser
facebook/pyre-check pull request #520
Opened 2021-11-01 14:11 UTC by abishekvashok

Clean up unclassified errors by mitigating each errors to corresponding
error types instead of a single unclassified error type.

Changes are done in such a way that the messages are made identical to
previous ones as much as possible. Thus, this is just a implementation
change which should have no effect on the output.

Updates a test in modelTest to contain to new test results given the
previous commit.

Test Plan
- Recompile the ocaml files from scratch:
```
cd scripts && ./setup.sh --local
cd source
make
```
- Run tests: `make tests` see all of them pass.
- Run pyre (with updated `PYRE_BINARY` pointing towards the exe file we just built)
`python3 -m client.pyre analyze`

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>
Fixes: https://github.com/MLH-Fellowship/pyre-check/issues/85

2021-11-01 14:11 UTC, abishekvashok commented
**Pre-submission checklist**
- [x] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
    - [x] `pre-commit run`
    - [x] `ocamlformat`

2021-11-01 18:39 UTC, arthaud requested changes
Nice!

2021-11-01 18:39 UTC, arthaud commented on source/interprocedural_analyses/taint/modelParser.ml
> +           (InvalidFindClauseType (Expression.show expression)))
Here and other places: could we just store the expression directly in the error? We already do that for `InvalidIdentifier` for instance.

2021-11-01 18:39 UTC, arthaud commented on source/interprocedural_analyses/taint/modelParser.ml
> +  let annotation_error_map error_message =
nitpick: Give those function better names.
`annotation_error` could be `model_verification_error`. It is a shortcut.
`annotation_error_map` could be `invalid_model_for_taint`.

2021-11-03 13:35 UTC, abishekvashok commented
Hey @arthaud thanks for the comments as usual :) Appreciate them, made the changes

2021-11-04 20:14 UTC, arthaud commented
Thanks, looks good to me! Could you rebase this on top of master? There are some conflicts.

2021-11-05 14:11 UTC, abishekvashok commented
@arthaud just rebased on top of master, but couldn't find conflicts!

2021-11-06 02:16 UTC, closed without merging