Adds boto3 models for AWS Lambda
facebook/pyre-check pull request #542
Opened 2021-11-23 12:35 UTC by abishekvashok

Adds RCE sink annotations of AWS Lambda which is a boto3 client.

Requires explicit type annotations and mypy_boto3 package being used to
annotate the code as boto3.client() returns `typing.any` because of the
large number of clients it contain. boto3 doesn't have any classes to
model as well (every client is literally the same class!)

Test plan:
- run pyre analyze --no-verify against the following code:
```python3
import flask
import boto3
from flask import Flask, render_template
from mypy_boto3_lambda import LambdaClient

app = Flask(__name__)

@app.route("/rce/<string:payload>")
def definite_rce(payload: str) -> None:
    client: LambdaClient = boto3.client('lambda')
    response = client.create_function(
        FunctionName='string',
        Runtime='nodejs',
        Role='string',
        Handler='string',
        Code={
            'ImageUri': payload
        },
        Description='string',
        Timeout=123,
        MemorySize=123,
        Publish=True,
        ImageConfig={
            'EntryPoint': [
                payload,
            ],
            'Command': [
                payload,
            ],
            'WorkingDirectory': payload
        },
    )
    response = client.update_function_code(
        FunctionName='string',
        ZipFile=b'bytes',
        S3Bucket=payload,
        S3Key='string',
        S3ObjectVersion='string',
        ImageUri='string',
        Publish=True,
        RevisionId='string',
        Architectures=[
        'x86_64'|'arm64',
        ]
    )
```

with the following `.pyre_configuration`:
```json
{
  "source_directories": [
    "."
  ],
  "taint_models_path": "../../stubs",
  "search_path": [
    ".",
    {"site-package": "boto3" },
    {"site-package": "mypy_boto3_lambda"}
  ]
}
```

Results:
<img width="1440" alt="Screenshot 2021-11-23 at 6 04 44 PM" src="https://user-images.githubusercontent.com/8947010/143024800-c89771d3-caa1-49f3-af76-e8b94ecfab7d.png">

Fixes part of https://github.com/MLH-Fellowship/pyre-check/issues/58
Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>

2021-11-23 17:20 UTC, pradeep90 commented
cc @0xedward @gbleaney @arthaud Do you have context here?

2021-11-23 17:37 UTC, abishekvashok commented
@pradeep90 https://github.com/MLH-Fellowship/pyre-check/issues/58

https://github.com/facebook/pyre-check/pull/536

I think these should contain the things you are looking for, but if not sorry! Is there anything particular you are looking for?

2021-11-23 18:29 UTC, r0rshark requested changes

2021-11-23 18:29 UTC, r0rshark commented on stubs/third_party_taint/boto3_clients_sources_sinks.pysa
> +def mypy_boto3_lambda.client.LambdaClient.update_function_code(ZipFile: TaintSink[RemoteCodeExecution], S3Bucket: TaintSink[RemoteCodeExecution], S3Key: TaintSink[RemoteCodeExecution], S3ObjectVersio
@abishekvashok  why S3Key and S3ObjectVersion are sink for RCE? :)

2021-11-24 05:01 UTC, abishekvashok commented on stubs/third_party_taint/boto3_clients_sources_sinks.pysa
> +def mypy_boto3_lambda.client.LambdaClient.update_function_code(ZipFile: TaintSink[RemoteCodeExecution], S3Bucket: TaintSink[RemoteCodeExecution], S3Key: TaintSink[RemoteCodeExecution], S3ObjectVersio
Ah... it's just me messing up 🤦  sorry. Reverted :)

2021-12-01 13:42 UTC, closed without merging

2021-12-01 19:28 UTC, 0xedward commented
Weird... It looks like this PR has been "merged" (https://github.com/facebook/pyre-check/commit/e6254a1c8a863f7615b4e50d83abd32ebb6ff91e) but the @facebook-github-bot didn't close this PR and comment about it.

Anyway, closing this PR because it has already been committed